# Generated by Django 4.2.15 on 2024-08-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_global_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_page',
            name='link_button',
            field=models.CharField(default='', max_length=30),
        ),
    ]
