# Generated by Django 4.2.15 on 2024-08-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_about_page_link_button'),
    ]

    operations = [
        migrations.RenameField(
            model_name='global_data',
            old_name='classes',
            new_name='counting',
        ),
        migrations.RenameField(
            model_name='global_data',
            old_name='graduates',
            new_name='counting_time',
        ),
        migrations.RemoveField(
            model_name='global_data',
            name='students',
        ),
        migrations.RemoveField(
            model_name='global_data',
            name='teachers',
        ),
        migrations.AddField(
            model_name='global_data',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
