# Generated by Django 4.2.15 on 2024-08-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_rename_classes_global_data_counting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('link_button', models.CharField(default='', max_length=30)),
                ('image', models.ImageField(upload_to='sections_images')),
            ],
        ),
    ]
