# Generated by Django 4.2.15 on 2024-08-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('second_name', models.CharField(max_length=32)),
                ('by_father', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('education', models.CharField(max_length=128)),
                ('subject', models.ManyToManyField(related_name='teachers', to='teachers.subjects')),
            ],
        ),
    ]
